//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112133.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dept()
        {
            this.Emp1 = new HashSet<Emp>();
        }
    
        public string dept_id { get; set; }
        public string dept_name { get; set; }
        public string dept_manager { get; set; }
    
        public virtual Emp Emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp> Emp1 { get; set; }
    }
}
