//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112133.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp()
        {
            this.dept = new HashSet<dept>();
            this.Equ = new HashSet<Equ>();
        }
    
        public string Emp_id { get; set; }
        public string Emp_pass { get; set; }
        public string Emp_name { get; set; }
        public string Emp_phone { get; set; }
        public Nullable<bool> Emp_manager { get; set; }
        public string Emp_dept { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dept> dept { get; set; }
        public virtual dept dept1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equ> Equ { get; set; }
    }
}
